@startuml

title __APP's Class Diagram__\n

  namespace com.example.user.exams {
    class com.example.user.exams.BuildConfig {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.ClassDocs {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.ClassPictures {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.Doc {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.DocAdapter {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.Image {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.ImageAdapter {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.MainActivity {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.Memo {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.MemoAdapter {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.MyBroadcastReceiver {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.MyClass {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.MyReminder {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.NewReminder {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.OpenPictures {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.ReminderWorker {
    }
  }
  

  namespace com.example.user.exams {
    class com.example.user.exams.StopWorker {
    }
  }
  

  com.example.user.exams.ClassDocs .up.|> android.view.View.OnClickListener
  com.example.user.exams.ClassDocs -up-|> android.app.Activity
  com.example.user.exams.ClassPictures .up.|> android.view.View.OnClickListener
  com.example.user.exams.ClassPictures -up-|> android.app.Activity
  com.example.user.exams.DocAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.user.exams.ImageAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.user.exams.MainActivity .up.|> android.view.View.OnClickListener
  com.example.user.exams.MainActivity -up-|> android.app.Activity
  com.example.user.exams.MemoAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  com.example.user.exams.MyBroadcastReceiver -up-|> android.content.BroadcastReceiver
  com.example.user.exams.MyClass .up.|> android.view.View.OnClickListener
  com.example.user.exams.MyClass -up-|> android.app.Activity
  com.example.user.exams.MyClass o-- com.example.user.exams.Memo : currentMemmo
  com.example.user.exams.MyReminder -up-|> android.app.Activity
  com.example.user.exams.NewReminder .up.|> android.view.View.OnClickListener
  com.example.user.exams.NewReminder -up-|> android.app.Activity
  com.example.user.exams.OpenPictures -up-|> android.app.Activity
  com.example.user.exams.ReminderWorker -up-|> androidx.work.Worker
  com.example.user.exams.StopWorker -up-|> androidx.work.Worker


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
